package com.atenea.dameals

import com.atenea.dameals.data.local.model.MealLocal
import com.atenea.dameals.data.remote.dto.MealDto
import com.atenea.dameals.domain.model.MealModel

fun mealLocalDataBuilder() =
    MealLocal(
        idMeal = "52772",
        strMeal = "Teriyaki Chicken Casserole",
        strDrinkAlternate = "",
        strCategory = "Chicken",
        strArea = "Japanese",
        strInstructions = "instructions",
        strMealThumb = "https=//www.themealdb.com/images/media/meals/wvpsxx1468256321.jpg",
        strTags = "Meat,Casserole",
        strYoutube = "https=//www.youtube.com/watch?v=4aZr5hZXP_s",
        strIngredient1 = "soy sauce",
        strIngredient2 = "water",
        strIngredient3 = "brown sugar",
        strIngredient4 = "ground ginger",
        strIngredient5 = "minced garlic",
        strIngredient6 = "cornstarch",
        strIngredient7 = "chicken breasts",
        strIngredient8 = "stir-fry vegetables",
        strIngredient9 = "brown rice",
        strIngredient10 = "",
        strIngredient11 = "",
        strIngredient12 = "",
        strIngredient13 = "",
        strIngredient14 = "",
        strIngredient15 = "",
        strIngredient16 = "",
        strIngredient17 = "",
        strIngredient18 = "",
        strIngredient19 = "",
        strIngredient20 = "",
        strMeasure1 = "3/4 cup",
        strMeasure2 = "1/2 cup",
        strMeasure3 = "1/4 cup",
        strMeasure4 = "1/2 teaspoon",
        strMeasure5 = "1/2 teaspoon",
        strMeasure6 = "4 Tablespoons",
        strMeasure7 = "2",
        strMeasure8 = "1 (12 oz.)",
        strMeasure9 = "3 cups",
        strMeasure10 = "",
        strMeasure11 = "",
        strMeasure12 = "",
        strMeasure13 = "",
        strMeasure14 = "",
        strMeasure15 = "",
        strMeasure16 = "",
        strMeasure17 = "",
        strMeasure18 = "",
        strMeasure19 = "",
        strMeasure20 = "",
        strSource = "",
        strImageSource = "",
        strCreativeCommonsConfirmed = "",
        dateModified = "",
        favorite = false
    )

fun mealDtoDataBuilder() =
    MealDto(
        idMeal = "52772",
        strMeal = "Teriyaki Chicken Casserole",
        strDrinkAlternate = "",
        strCategory = "Chicken",
        strArea = "Japanese",
        strInstructions = "instructions",
        strMealThumb = "https=//www.themealdb.com/images/media/meals/wvpsxx1468256321.jpg",
        strTags = "Meat,Casserole",
        strYoutube = "https=//www.youtube.com/watch?v=4aZr5hZXP_s",
        strIngredient1 = "soy sauce",
        strIngredient2 = "water",
        strIngredient3 = "brown sugar",
        strIngredient4 = "ground ginger",
        strIngredient5 = "minced garlic",
        strIngredient6 = "cornstarch",
        strIngredient7 = "chicken breasts",
        strIngredient8 = "stir-fry vegetables",
        strIngredient9 = "brown rice",
        strIngredient10 = "",
        strIngredient11 = "",
        strIngredient12 = "",
        strIngredient13 = "",
        strIngredient14 = "",
        strIngredient15 = "",
        strIngredient16 = "",
        strIngredient17 = "",
        strIngredient18 = "",
        strIngredient19 = "",
        strIngredient20 = "",
        strMeasure1 = "3/4 cup",
        strMeasure2 = "1/2 cup",
        strMeasure3 = "1/4 cup",
        strMeasure4 = "1/2 teaspoon",
        strMeasure5 = "1/2 teaspoon",
        strMeasure6 = "4 Tablespoons",
        strMeasure7 = "2",
        strMeasure8 = "1 (12 oz.)",
        strMeasure9 = "3 cups",
        strMeasure10 = "",
        strMeasure11 = "",
        strMeasure12 = "",
        strMeasure13 = "",
        strMeasure14 = "",
        strMeasure15 = "",
        strMeasure16 = "",
        strMeasure17 = "",
        strMeasure18 = "",
        strMeasure19 = "",
        strMeasure20 = "",
        strSource = "",
        strImageSource = "",
        strCreativeCommonsConfirmed = "",
        dateModified = ""
    )

fun mealModelDataBuilder() =
    MealModel(
        idMeal = "52772",
        strMeal = "Teriyaki Chicken Casserole",
        strDrinkAlternate = "",
        strCategory = "Chicken",
        strArea = "Japanese",
        strInstructions = "instructions",
        strMealThumb = "https=//www.themealdb.com/images/media/meals/wvpsxx1468256321.jpg",
        strTags = "Meat,Casserole",
        strYoutube = "https=//www.youtube.com/watch?v=4aZr5hZXP_s",
        strIngredient1 = "soy sauce",
        strIngredient2 = "water",
        strIngredient3 = "brown sugar",
        strIngredient4 = "ground ginger",
        strIngredient5 = "minced garlic",
        strIngredient6 = "cornstarch",
        strIngredient7 = "chicken breasts",
        strIngredient8 = "stir-fry vegetables",
        strIngredient9 = "brown rice",
        strIngredient10 = "",
        strIngredient11 = "",
        strIngredient12 = "",
        strIngredient13 = "",
        strIngredient14 = "",
        strIngredient15 = "",
        strIngredient16 = "",
        strIngredient17 = "",
        strIngredient18 = "",
        strIngredient19 = "",
        strIngredient20 = "",
        strMeasure1 = "3/4 cup",
        strMeasure2 = "1/2 cup",
        strMeasure3 = "1/4 cup",
        strMeasure4 = "1/2 teaspoon",
        strMeasure5 = "1/2 teaspoon",
        strMeasure6 = "4 Tablespoons",
        strMeasure7 = "2",
        strMeasure8 = "1 (12 oz.)",
        strMeasure9 = "3 cups",
        strMeasure10 = "",
        strMeasure11 = "",
        strMeasure12 = "",
        strMeasure13 = "",
        strMeasure14 = "",
        strMeasure15 = "",
        strMeasure16 = "",
        strMeasure17 = "",
        strMeasure18 = "",
        strMeasure19 = "",
        strMeasure20 = "",
        strSource = "",
        strImageSource = "",
        strCreativeCommonsConfirmed = "",
        dateModified = ""
    )

fun buildMealList(numElements: Int): List<MealModel> {
    val list = mutableListOf<MealModel>()

    for (i in 0 until numElements ) {
        list.add(
            mealModelDataBuilder()
        )
    }
    list[0].favorite = true
    return list.toList()
}